import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BreakingNews from '../BreakingNews/BreakingNews.js'
import HotTopics from '../components/HotTopics/HotTopics.js'
import Trending from '../components/Trending/Trending'


export default function Home() {
  return (
    <div >
      <Head>
        <title>News-Express</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BreakingNews />
      <div style={{display:"flex"}}>
        <HotTopics />
        <Trending/>
    </div>
      
    </div>
  )
}
